name: Repack initramfs

on:
  push:
    paths:
      - "src/**"

jobs:
  repack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Repack initramfs
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: initramfs
          path: build/initramfs.cpio.gz
          retention-days: 5
